main:
  - name: Blog
    url: /#blog
    weight: 10
  - name: Tech Sandbox
    url: /#tech-sandbox
    weight: 20
  - name: Skills
    url: /#skills
    weight: 30
  - name: Experience
    url: /#experience
    weight: 40
  - name: Contact
    url: /#contact
    weight: 50
